apiVersion: v2
name: higress-console
description: Management console for WntASG (AISecGw)
type: application
version: 2.2.4
sources:
  - https://github.com/flx0002g/AISecGw-console
appVersion: "V100R001C01B010"
